# Generated by Django 5.0.13 on 2025-03-13 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Completed')], default='ACTIVE', max_length=10)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('USER', 'User'), ('AI', 'Ai')], default='USER', max_length=10)),
                ('model', models.CharField(choices=[('gpt-4', 'Gpt 4'), ('gpt-4o', 'Gpt 4O'), ('gpt-4o-mini', 'Gpt 4O Mini'), ('o1', 'O1'), ('o1-pro-mode', 'O1 Pro Mode'), ('o3-mini', 'O3 Mini'), ('o3-mini-high', 'O3 Mini High'), ('gpt-4.5', 'Gpt 4 5')], default='gpt-4o', max_length=20)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
