# Generated by Django 5.0.13 on 2025-03-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='model_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_2', to='ai_model.modelversion'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='ai_model.aimodel'),
        ),
    ]
