# Generated by Django 5.0.13 on 2025-03-17 07:48

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_dialogue_model_version_alter_dialogue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
