# Generated by Django 5.0.13 on 2025-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='model',
            field=models.CharField(choices=[('gpt-4', 'Gpt 4'), ('gpt-4o', 'Gpt 4O'), ('gpt-4o-mini', 'Gpt 4O Mini'), ('o1', 'O1'), ('o1-pro-mode', 'O1 Pro Mode'), ('o3-mini', 'O3 Mini'), ('o3-mini-high', 'O3 Mini High'), ('gpt-4.5', 'Gpt 4 5')], default='gpt-4o', max_length=20),
        ),
        migrations.AddField(
            model_name='dialog',
            name='type',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'Ai')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='dialog',
            name='updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Completed')], default='ACTIVE', max_length=10),
        ),
    ]
