# Generated by Django 5.0.13 on 2025-03-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chatgpt', 'Chatgpt'), ('llama', 'Llama')], default='chatgpt', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_model.aimodel')),
            ],
        ),
    ]
